package com.example.myapplication.model;


import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "Admin")
public class Admin {

    // id is generated by the database and set on the object automagically
    @DatabaseField()
    public int id;
    @DatabaseField()
    public String name;

    private Dao<Admin, Integer> AdminDao;

    Admin() {
        // needed by ormlite
    }

    public Admin(int id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id=").append(id);
        sb.append(", ").append("Name=").append(name);
        return sb.toString();
    }

}
